name: gofit
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.5
  rflutter_alert: ^2.0.4
  cupertino_icons: ^1.0.2
  liquid_pull_to_refresh: ^3.0.1
  flutter_login: ^2.1.0
  flutter_hooks: ^0.18.0
  # flutter_native_splash: ^2.3.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# flutter_native_splash:
#   color: "#42a5f5"
#   image: assets/gofit-logo.png
#   android: true
#   ios: false
#   web: false

flutter:

  uses-material-design: true
  assets:
    - assets/gofit-logo.png
    - assets/gofit-transparent.png
    - assets/transparent-logo.png